/* Auto-generated by scripts/generate-builtin-media.mjs — do not edit by hand. */
import type { ProjectAsset } from './types'

/** Paths under Vite public/ (resolved via preview <base href>). */
export const BUILTIN_MEDIA = {
  photo: './media/photo.svg',
  sprite: './media/sprite.svg',
  avatar: './media/avatar.svg',
  banner: './media/banner.svg',
  poster: './media/poster.svg',
  bg_sky: './media/bg_sky.svg',
  bg_campus: './media/bg_campus.svg',
  bg_night: './media/bg_night.svg',
  icon_star: './media/icon_star.svg',
  icon_heart: './media/icon_heart.svg',
  icon_check: './media/icon_check.svg',
  icon_coin: './media/icon_coin.svg',
  icon_tree: './media/icon_tree.svg',
  icon_cat: './media/icon_cat.svg',
  icon_ball: './media/icon_ball.svg',
  icon_flag: './media/icon_flag.svg',
  icon_trophy: './media/icon_trophy.svg',
  icon_plant: './media/icon_plant.svg',
  icon_book: './media/icon_book.svg',
  btn_play: './media/btn_play.svg',
  beep: './media/beep.wav',
  chime: './media/chime.wav',
  pop: './media/pop.wav',
  click: './media/click.wav',
  fail: './media/fail.wav',
  coin: './media/coin.wav',
  win: './media/win.wav',
  alarm: './media/alarm.wav',
  video: './media/clip.mp4',
} as const

export type BuiltinMediaKey = keyof typeof BUILTIN_MEDIA

const ASSET_META: Array<{ name: string; mime: string; key: BuiltinMediaKey }> = [
    { name: '内置·校园风景.svg', mime: 'image/svg+xml', key: 'photo' },
    { name: '内置·笑脸精灵.svg', mime: 'image/svg+xml', key: 'sprite' },
    { name: '内置·同学头像.svg', mime: 'image/svg+xml', key: 'avatar' },
    { name: '内置·横幅.svg', mime: 'image/svg+xml', key: 'banner' },
    { name: '内置·视频封面.svg', mime: 'image/svg+xml', key: 'poster' },
    { name: '内置·天空背景.svg', mime: 'image/svg+xml', key: 'bg_sky' },
    { name: '内置·校园背景.svg', mime: 'image/svg+xml', key: 'bg_campus' },
    { name: '内置·夜空背景.svg', mime: 'image/svg+xml', key: 'bg_night' },
    { name: '内置·星星.svg', mime: 'image/svg+xml', key: 'icon_star' },
    { name: '内置·爱心.svg', mime: 'image/svg+xml', key: 'icon_heart' },
    { name: '内置·对勾.svg', mime: 'image/svg+xml', key: 'icon_check' },
    { name: '内置·金币.svg', mime: 'image/svg+xml', key: 'icon_coin' },
    { name: '内置·小树.svg', mime: 'image/svg+xml', key: 'icon_tree' },
    { name: '内置·小猫.svg', mime: 'image/svg+xml', key: 'icon_cat' },
    { name: '内置·皮球.svg', mime: 'image/svg+xml', key: 'icon_ball' },
    { name: '内置·旗帜.svg', mime: 'image/svg+xml', key: 'icon_flag' },
    { name: '内置·奖杯.svg', mime: 'image/svg+xml', key: 'icon_trophy' },
    { name: '内置·盆栽.svg', mime: 'image/svg+xml', key: 'icon_plant' },
    { name: '内置·书本.svg', mime: 'image/svg+xml', key: 'icon_book' },
    { name: '内置·播放钮.svg', mime: 'image/svg+xml', key: 'btn_play' },
    { name: '内置·提示音.wav', mime: 'audio/wav', key: 'beep' },
    { name: '内置·成功音.wav', mime: 'audio/wav', key: 'chime' },
    { name: '内置·轻点音.wav', mime: 'audio/wav', key: 'pop' },
    { name: '内置·点击音.wav', mime: 'audio/wav', key: 'click' },
    { name: '内置·失败音.wav', mime: 'audio/wav', key: 'fail' },
    { name: '内置·得分音.wav', mime: 'audio/wav', key: 'coin' },
    { name: '内置·胜利音.wav', mime: 'audio/wav', key: 'win' },
    { name: '内置·闹钟音.wav', mime: 'audio/wav', key: 'alarm' },
    { name: '内置·短视频.mp4', mime: 'video/mp4', key: 'video' },
]

/** Default media pack attached to every builtin template. */
export function createBuiltinProjectAssets(): ProjectAsset[] {
  const now = Date.now()
  return ASSET_META.map((it, i) => ({
    id: `builtin_${it.key}`,
    name: it.name,
    mime: it.mime,
    dataUrl: BUILTIN_MEDIA[it.key],
    createdAt: now + i,
  }))
}

/** 旧工程补上新内置资源，不覆盖学生自己上传的。 */
export function mergeBuiltinAssets(assets: ProjectAsset[]): ProjectAsset[] {
  const pack = createBuiltinProjectAssets()
  const ids = new Set(assets.map((a) => a.id))
  const urls = new Set(assets.map((a) => a.dataUrl))
  const extra = pack.filter((b) => !ids.has(b.id) && !urls.has(b.dataUrl))
  return extra.length ? [...assets, ...extra] : assets
}

export function isBuiltinAssetId(id: string): boolean {
  return id.startsWith('builtin_')
}
