import type { ComponentType } from '@/project/types'

export type ComponentCategory = 'user' | 'layout' | 'media' | 'fun' | 'sensors' | 'storage' | 'misc'

export interface PropField {
  key: string
  label: string
  kind: 'text' | 'number' | 'boolean' | 'color' | 'select' | 'asset'
  options?: { value: string; label: string }[]
}

export interface ComponentMeta {
  type: ComponentType
  label: string
  category: ComponentCategory
  isVisible: boolean
  isContainer: boolean
  defaults: Record<string, unknown>
  fields: PropField[]
  events: string[]
  methods: string[]
}

/** 组件库分类展示顺序与说明 */
export const CATEGORY_META: Record<
  ComponentCategory,
  { label: string; hint: string; icon: string }
> = {
  user: { label: '界面控件', hint: '按钮、闹钟、日历、待办、计算器、天气…', icon: '▣' },
  layout: { label: '布局', hint: '水平/垂直/表格/滚动/卡片/占位', icon: '⊞' },
  media: { label: '媒体绘图', hint: '图片、画布、音视频、相机、图库、语音', icon: '▶' },
  fun: { label: '趣味互动', hint: '骰子、硬币、记分、LED、交通灯…', icon: '🎲' },
  storage: { label: '数据网络', hint: '笔记、选文件、文件夹、本地库、导出…', icon: '💾' },
  sensors: { label: '传感器', hint: '加速度、指南针、定位、电量、网络、摇一摇', icon: '📡' },
  misc: { label: '工具', hint: '通知、时钟、短信邮件、手电筒、震动、剪贴板…', icon: '🔧' },
}

export const CATEGORY_ORDER: ComponentCategory[] = [
  'user',
  'layout',
  'media',
  'fun',
  'storage',
  'sensors',
  'misc',
]

const sizeOpts = [
  { value: '自动', label: '自动' },
  { value: '填满父组件', label: '填满父组件' },
]

function localISODate() {
  const d = new Date()
  const p = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`
}

export const COMPONENT_REGISTRY: Record<string, ComponentMeta> = {
  Button: {
    type: 'Button',
    label: '按钮',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Text: '按钮', BackgroundColor: '#009688', TextColor: '#ffffff', FontSize: 14, Enabled: true, Width: '自动', Height: '自动' },
    fields: [
      { key: 'Text', label: '文本', kind: 'text' },
      { key: 'BackgroundColor', label: '背景色', kind: 'color' },
      { key: 'TextColor', label: '文字色', kind: 'color' },
      { key: 'FontSize', label: '字号', kind: 'number' },
      { key: 'Enabled', label: '启用', kind: 'boolean' },
      { key: 'Width', label: '宽度', kind: 'select', options: sizeOpts },
      { key: 'Height', label: '高度', kind: 'select', options: sizeOpts },
    ],
    events: ['Click', 'LongClick'],
    methods: [],
  },
  Label: {
    type: 'Label',
    label: '标签',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Text: '标签', TextColor: '#202124', FontSize: 16, Width: '填满父组件', Height: '自动' },
    fields: [
      { key: 'Text', label: '文本', kind: 'text' },
      { key: 'TextColor', label: '文字色', kind: 'color' },
      { key: 'FontSize', label: '字号', kind: 'number' },
      { key: 'Width', label: '宽度', kind: 'select', options: sizeOpts },
    ],
    events: [],
    methods: [],
  },
  TextBox: {
    type: 'TextBox',
    label: '文本框',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Text: '', Hint: '请输入', FontSize: 14, Width: '填满父组件', Height: '自动', Enabled: true },
    fields: [
      { key: 'Text', label: '文本', kind: 'text' },
      { key: 'Hint', label: '提示', kind: 'text' },
      { key: 'FontSize', label: '字号', kind: 'number' },
      { key: 'Enabled', label: '启用', kind: 'boolean' },
    ],
    events: ['GotFocus', 'LostFocus'],
    methods: [],
  },
  PasswordTextBox: {
    type: 'PasswordTextBox',
    label: '密码框',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Text: '', Hint: '请输入密码', FontSize: 14, Width: '填满父组件', Enabled: true },
    fields: [
      { key: 'Text', label: '文本', kind: 'text' },
      { key: 'Hint', label: '提示', kind: 'text' },
      { key: 'Enabled', label: '启用', kind: 'boolean' },
    ],
    events: ['GotFocus', 'LostFocus'],
    methods: [],
  },
  CheckBox: {
    type: 'CheckBox',
    label: '复选框',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Text: '选项', Checked: false, Enabled: true },
    fields: [
      { key: 'Text', label: '文本', kind: 'text' },
      { key: 'Checked', label: '选中', kind: 'boolean' },
      { key: 'Enabled', label: '启用', kind: 'boolean' },
    ],
    events: ['Changed'],
    methods: [],
  },
  Switch: {
    type: 'Switch',
    label: '开关',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Text: '开关', On: false, Enabled: true },
    fields: [
      { key: 'Text', label: '文本', kind: 'text' },
      { key: 'On', label: '开启', kind: 'boolean' },
      { key: 'Enabled', label: '启用', kind: 'boolean' },
    ],
    events: ['Changed'],
    methods: [],
  },
  Slider: {
    type: 'Slider',
    label: '滑块',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { MinValue: 0, MaxValue: 100, ThumbPosition: 50, Width: '填满父组件' },
    fields: [
      { key: 'MinValue', label: '最小', kind: 'number' },
      { key: 'MaxValue', label: '最大', kind: 'number' },
      { key: 'ThumbPosition', label: '位置', kind: 'number' },
    ],
    events: ['PositionChanged'],
    methods: [],
  },
  Spinner: {
    type: 'Spinner',
    label: '下拉框',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { ElementsFromString: '选项A,选项B,选项C', Selection: '选项A', Width: '填满父组件' },
    fields: [
      { key: 'ElementsFromString', label: '选项(逗号分隔)', kind: 'text' },
      { key: 'Selection', label: '当前选中', kind: 'text' },
    ],
    events: ['AfterSelecting'],
    methods: [],
  },
  DatePicker: {
    type: 'DatePicker',
    label: '日期选择',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Date: '', Width: '填满父组件' },
    fields: [{ key: 'Date', label: '日期', kind: 'text' }],
    events: ['AfterDateSet'],
    methods: [],
  },
  TimePicker: {
    type: 'TimePicker',
    label: '时间选择',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Time: '', Width: '填满父组件' },
    fields: [{ key: 'Time', label: '时间', kind: 'text' }],
    events: ['AfterTimeSet'],
    methods: [],
  },
  Image: {
    type: 'Image',
    label: '图片',
    category: 'media',
    isVisible: true,
    isContainer: false,
    defaults: { Picture: './media/photo.png', Width: 120, Height: 80, ScalePictureToFit: true },
    fields: [
      { key: 'Picture', label: '图片', kind: 'asset' },
      { key: 'Width', label: '宽度', kind: 'number' },
      { key: 'Height', label: '高度', kind: 'number' },
    ],
    events: ['Click'],
    methods: [],
  },
  ListView: {
    type: 'ListView',
    label: '列表',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { ElementsFromString: '项目1,项目2,项目3', Width: '填满父组件', Height: 160 },
    fields: [
      { key: 'ElementsFromString', label: '列表项(逗号分隔)', kind: 'text' },
      { key: 'Height', label: '高度', kind: 'number' },
    ],
    events: ['AfterPicking'],
    methods: ['SetElementsFromString'],
  },
  HorizontalArrangement: {
    type: 'HorizontalArrangement',
    label: '水平布局',
    category: 'layout',
    isVisible: true,
    isContainer: true,
    defaults: { Width: '填满父组件', Height: '自动', AlignHorizontal: 'left', BackgroundColor: 'transparent' },
    fields: [
      { key: 'BackgroundColor', label: '背景色', kind: 'color' },
      { key: 'Width', label: '宽度', kind: 'select', options: sizeOpts },
    ],
    events: [],
    methods: [],
  },
  VerticalArrangement: {
    type: 'VerticalArrangement',
    label: '垂直布局',
    category: 'layout',
    isVisible: true,
    isContainer: true,
    defaults: { Width: '填满父组件', Height: '自动', BackgroundColor: 'transparent' },
    fields: [
      { key: 'BackgroundColor', label: '背景色', kind: 'color' },
      { key: 'Width', label: '宽度', kind: 'select', options: sizeOpts },
    ],
    events: [],
    methods: [],
  },
  TableArrangement: {
    type: 'TableArrangement',
    label: '表格布局',
    category: 'layout',
    isVisible: true,
    isContainer: true,
    defaults: { Columns: 2, Rows: 2, Width: '填满父组件', Height: '自动' },
    fields: [
      { key: 'Columns', label: '列数', kind: 'number' },
      { key: 'Rows', label: '行数', kind: 'number' },
    ],
    events: [],
    methods: [],
  },
  Canvas: {
    type: 'Canvas',
    label: '画布',
    category: 'media',
    isVisible: true,
    isContainer: false,
    defaults: { Width: '填满父组件', Height: 200, BackgroundColor: '#e8eaed' },
    fields: [
      { key: 'BackgroundColor', label: '背景色', kind: 'color' },
      { key: 'Height', label: '高度', kind: 'number' },
    ],
    events: ['Touched', 'Dragged'],
    methods: ['Clear', 'DrawLine'],
  },
  Ball: {
    type: 'Ball',
    label: '小球',
    category: 'fun',
    isVisible: true,
    isContainer: false,
    defaults: { X: 20, Y: 20, Radius: 16, PaintColor: '#009688', Width: 40, Height: 40 },
    fields: [
      { key: 'X', label: 'X', kind: 'number' },
      { key: 'Y', label: 'Y', kind: 'number' },
      { key: 'Radius', label: '半径', kind: 'number' },
      { key: 'PaintColor', label: '颜色', kind: 'color' },
    ],
    events: ['Touched', 'Flung'],
    methods: ['MoveTo'],
  },
  ImageSprite: {
    type: 'ImageSprite',
    label: '精灵图',
    category: 'fun',
    isVisible: true,
    isContainer: false,
    defaults: { X: 10, Y: 10, Width: 64, Height: 64, Picture: './media/sprite.png' },
    fields: [
      { key: 'X', label: 'X', kind: 'number' },
      { key: 'Y', label: 'Y', kind: 'number' },
      { key: 'Width', label: '宽度', kind: 'number' },
      { key: 'Height', label: '高度', kind: 'number' },
      { key: 'Picture', label: '图片', kind: 'asset' },
    ],
    events: ['Touched', 'Flung'],
    methods: ['MoveTo'],
  },
  WebViewer: {
    type: 'WebViewer',
    label: '网页浏览',
    category: 'media',
    isVisible: true,
    isContainer: false,
    defaults: { HomeUrl: '', Width: '填满父组件', Height: 240 },
    fields: [
      { key: 'HomeUrl', label: '网址（建议 https）', kind: 'text' },
      { key: 'Height', label: '高度', kind: 'number' },
    ],
    events: ['PageLoaded'],
    methods: ['GoToUrl'],
  },
  ProgressBar: {
    type: 'ProgressBar',
    label: '进度条',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Progress: 0, Width: '填满父组件', Height: 8 },
    fields: [
      { key: 'Progress', label: '进度0-100', kind: 'number' },
      { key: 'Width', label: '宽度', kind: 'select', options: sizeOpts },
    ],
    events: [],
    methods: [],
  },
  Player: {
    type: 'Player',
    label: '播放器',
    category: 'media',
    isVisible: true,
    isContainer: false,
    defaults: { Source: './media/chime.wav', Volume: 50, Width: '填满父组件' },
    fields: [
      { key: 'Source', label: '音频', kind: 'asset' },
      { key: 'Volume', label: '音量0-100', kind: 'number' },
    ],
    events: ['Completed'],
    methods: ['Start', 'Pause', 'Stop'],
  },
  VideoPlayer: {
    type: 'VideoPlayer',
    label: '视频播放器',
    category: 'media',
    isVisible: true,
    isContainer: false,
    defaults: { Source: './media/clip.mp4', Width: '填满父组件', Height: 200 },
    fields: [
      { key: 'Source', label: '视频', kind: 'asset' },
      { key: 'Width', label: '宽度', kind: 'select', options: sizeOpts },
      { key: 'Height', label: '高度', kind: 'number' },
    ],
    events: ['Completed'],
    methods: ['Start', 'Pause', 'Stop'],
  },
  Sound: {
    type: 'Sound',
    label: '音效',
    category: 'media',
    isVisible: false,
    isContainer: false,
    defaults: { Source: './media/beep.wav' },
    fields: [{ key: 'Source', label: '音效', kind: 'asset' }],
    events: [],
    methods: ['Play'],
  },
  RatingBar: {
    type: 'RatingBar',
    label: '评分条',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Rating: 3, MaxRating: 5, Width: '填满父组件' },
    fields: [
      { key: 'Rating', label: '评分', kind: 'number' },
      { key: 'MaxRating', label: '满分', kind: 'number' },
    ],
    events: ['Changed'],
    methods: [],
  },
  Notifier: {
    type: 'Notifier',
    label: '通知器',
    category: 'misc',
    isVisible: false,
    isContainer: false,
    defaults: {},
    fields: [],
    events: ['AfterChoosing'],
    methods: ['ShowAlert', 'ShowMessageDialog', 'ShowChooseDialog'],
  },
  Clock: {
    type: 'Clock',
    label: '时钟',
    category: 'misc',
    isVisible: false,
    isContainer: false,
    defaults: { TimerInterval: 1000, TimerEnabled: false },
    fields: [
      { key: 'TimerInterval', label: '间隔(ms)', kind: 'number' },
      { key: 'TimerEnabled', label: '启用计时', kind: 'boolean' },
    ],
    events: ['Timer'],
    methods: ['SystemTime'],
  },
  TinyDB: {
    type: 'TinyDB',
    label: '本地数据库',
    category: 'storage',
    isVisible: false,
    isContainer: false,
    defaults: { Namespace: 'default' },
    fields: [{ key: 'Namespace', label: '命名空间', kind: 'text' }],
    events: [],
    methods: ['StoreValue', 'GetValue', 'ClearTag', 'ClearAll'],
  },
  TinyWebDB: {
    type: 'TinyWebDB',
    label: '网络数据库',
    category: 'storage',
    isVisible: false,
    isContainer: false,
    defaults: { ServiceURL: '' },
    fields: [{ key: 'ServiceURL', label: '服务地址(可空=本地模拟)', kind: 'text' }],
    events: ['GotValue', 'ValueStored'],
    methods: ['StoreValue', 'GetValue'],
  },
  Web: {
    type: 'Web',
    label: '网页请求',
    category: 'storage',
    isVisible: false,
    isContainer: false,
    defaults: { Url: '', ResponseContent: '' },
    fields: [{ key: 'Url', label: '默认网址', kind: 'text' }],
    events: ['GotText'],
    methods: ['Get'],
  },
  TextToSpeech: {
    type: 'TextToSpeech',
    label: '文字转语音',
    category: 'media',
    isVisible: false,
    isContainer: false,
    defaults: { Language: 'zh-CN' },
    fields: [{ key: 'Language', label: '语言', kind: 'text' }],
    events: [],
    methods: ['Speak'],
  },
  SpeechRecognizer: {
    type: 'SpeechRecognizer',
    label: '语音识别',
    category: 'media',
    isVisible: false,
    isContainer: false,
    defaults: { Language: 'zh-CN', Result: '' },
    fields: [{ key: 'Language', label: '语言', kind: 'text' }],
    events: ['AfterGettingText'],
    methods: ['GetText'],
  },
  Sharing: {
    type: 'Sharing',
    label: '分享',
    category: 'misc',
    isVisible: false,
    isContainer: false,
    defaults: {},
    fields: [],
    events: [],
    methods: ['ShareMessage'],
  },
  ActivityStarter: {
    type: 'ActivityStarter',
    label: '活动启动器',
    category: 'misc',
    isVisible: false,
    isContainer: false,
    defaults: { Action: '', DataUri: '' },
    fields: [
      { key: 'Action', label: '动作(可空)', kind: 'text' },
      { key: 'DataUri', label: '默认网址', kind: 'text' },
    ],
    events: [],
    methods: ['StartActivity'],
  },
  PhoneCall: {
    type: 'PhoneCall',
    label: '电话',
    category: 'misc',
    isVisible: false,
    isContainer: false,
    defaults: { PhoneNumber: '' },
    fields: [{ key: 'PhoneNumber', label: '电话号码', kind: 'text' }],
    events: [],
    methods: ['MakePhoneCall'],
  },
  AccelerometerSensor: {
    type: 'AccelerometerSensor',
    label: '加速度传感器',
    category: 'sensors',
    isVisible: false,
    isContainer: false,
    defaults: { Enabled: true, XAccel: 0, YAccel: 0, ZAccel: 0 },
    fields: [{ key: 'Enabled', label: '启用', kind: 'boolean' }],
    events: ['AccelerationChanged'],
    methods: [],
  },
  OrientationSensor: {
    type: 'OrientationSensor',
    label: '方向传感器',
    category: 'sensors',
    isVisible: false,
    isContainer: false,
    defaults: { Enabled: true, Angle: 0, Pitch: 0, Roll: 0 },
    fields: [{ key: 'Enabled', label: '启用', kind: 'boolean' }],
    events: ['OrientationChanged'],
    methods: [],
  },
  LocationSensor: {
    type: 'LocationSensor',
    label: '定位传感器',
    category: 'sensors',
    isVisible: false,
    isContainer: false,
    defaults: {
      Enabled: false,
      Latitude: 0,
      Longitude: 0,
      Altitude: 0,
      Accuracy: 0,
      Speed: 0,
    },
    fields: [{ key: 'Enabled', label: '启用', kind: 'boolean' }],
    events: ['LocationChanged'],
    methods: [],
  },
  Camera: {
    type: 'Camera',
    label: '相机',
    category: 'media',
    isVisible: false,
    isContainer: false,
    defaults: { Picture: '' },
    fields: [],
    events: ['AfterPicture'],
    methods: ['TakePicture'],
  },
  Dice: {
    type: 'Dice',
    label: '骰子',
    category: 'fun',
    isVisible: true,
    isContainer: false,
    defaults: { Result: 1, Sides: 6 },
    fields: [
      { key: 'Sides', label: '面数', kind: 'number' },
      { key: 'Result', label: '当前点数', kind: 'number' },
    ],
    events: ['Click', 'Rolled'],
    methods: ['Roll'],
  },
  Marquee: {
    type: 'Marquee',
    label: '走马灯',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Text: '欢迎来到 Mixly 课堂 ★ ', Speed: 6, TextColor: '#009688', BackgroundColor: '#e0f2f1', Width: '填满父组件', Height: 36 },
    fields: [
      { key: 'Text', label: '文本', kind: 'text' },
      { key: 'Speed', label: '速度(秒越慢)', kind: 'number' },
      { key: 'TextColor', label: '文字色', kind: 'color' },
      { key: 'BackgroundColor', label: '背景色', kind: 'color' },
    ],
    events: [],
    methods: [],
  },
  ColorPicker: {
    type: 'ColorPicker',
    label: '颜色选择',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Color: '#009688', Width: '自动' },
    fields: [{ key: 'Color', label: '颜色', kind: 'color' }],
    events: ['Changed'],
    methods: [],
  },
  Countdown: {
    type: 'Countdown',
    label: '倒计时',
    category: 'fun',
    isVisible: true,
    isContainer: false,
    defaults: { Seconds: 10, Remaining: 10, Running: false, TextColor: '#c62828', FontSize: 28, Width: '填满父组件' },
    fields: [
      { key: 'Seconds', label: '总秒数', kind: 'number' },
      { key: 'Remaining', label: '剩余秒数', kind: 'number' },
      { key: 'FontSize', label: '字号', kind: 'number' },
      { key: 'TextColor', label: '文字色', kind: 'color' },
    ],
    events: ['Tick', 'Finished'],
    methods: ['Start', 'Pause', 'Reset'],
  },
  Stopwatch: {
    type: 'Stopwatch',
    label: '秒表',
    category: 'fun',
    isVisible: true,
    isContainer: false,
    defaults: { Elapsed: 0, Running: false, TextColor: '#1565c0', FontSize: 28, Width: '填满父组件' },
    fields: [
      { key: 'Elapsed', label: '已过秒数', kind: 'number' },
      { key: 'FontSize', label: '字号', kind: 'number' },
      { key: 'TextColor', label: '文字色', kind: 'color' },
    ],
    events: ['Tick'],
    methods: ['Start', 'Pause', 'Reset'],
  },
  QRCode: {
    type: 'QRCode',
    label: '二维码',
    category: 'fun',
    isVisible: true,
    isContainer: false,
    defaults: { Text: 'https://www.bilibili.com', Size: 140 },
    fields: [
      { key: 'Text', label: '内容', kind: 'text' },
      { key: 'Size', label: '边长(px)', kind: 'number' },
    ],
    events: [],
    methods: ['Refresh'],
  },
  Joystick: {
    type: 'Joystick',
    label: '虚拟摇杆',
    category: 'fun',
    isVisible: true,
    isContainer: false,
    defaults: { X: 0, Y: 0, Size: 120 },
    fields: [
      { key: 'Size', label: '尺寸(px)', kind: 'number' },
      { key: 'X', label: 'X(-1~1)', kind: 'number' },
      { key: 'Y', label: 'Y(-1~1)', kind: 'number' },
    ],
    events: ['PositionChanged', 'Released'],
    methods: [],
  },
  ChatBubble: {
    type: 'ChatBubble',
    label: '聊天气泡',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: {
      Text: '你好呀！',
      Side: '左',
      BackgroundColor: '#e0f2f1',
      TextColor: '#202124',
      FontSize: 14,
      Width: '填满父组件',
    },
    fields: [
      { key: 'Text', label: '文本', kind: 'text' },
      {
        key: 'Side',
        label: '朝向',
        kind: 'select',
        options: [
          { value: '左', label: '左' },
          { value: '右', label: '右' },
        ],
      },
      { key: 'BackgroundColor', label: '气泡色', kind: 'color' },
      { key: 'TextColor', label: '文字色', kind: 'color' },
      { key: 'FontSize', label: '字号', kind: 'number' },
    ],
    events: ['Click'],
    methods: [],
  },
  Celebration: {
    type: 'Celebration',
    label: '庆祝特效',
    category: 'fun',
    isVisible: false,
    isContainer: false,
    defaults: { Duration: 1800 },
    fields: [{ key: 'Duration', label: '时长(ms)', kind: 'number' }],
    events: [],
    methods: ['Celebrate'],
  },
  TextArea: {
    type: 'TextArea',
    label: '多行文本',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Text: '', Hint: '请输入多行内容', Height: 96, Width: '填满父组件', Enabled: true },
    fields: [
      { key: 'Text', label: '文本', kind: 'text' },
      { key: 'Hint', label: '提示', kind: 'text' },
      { key: 'Height', label: '高度', kind: 'number' },
      { key: 'Enabled', label: '启用', kind: 'boolean' },
    ],
    events: ['GotFocus', 'LostFocus'],
    methods: [],
  },
  NumberBox: {
    type: 'NumberBox',
    label: '数字框',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Text: '0', Hint: '请输入数字', Width: '填满父组件', Enabled: true },
    fields: [
      { key: 'Text', label: '数值', kind: 'text' },
      { key: 'Hint', label: '提示', kind: 'text' },
      { key: 'Enabled', label: '启用', kind: 'boolean' },
    ],
    events: ['GotFocus', 'LostFocus', 'Changed'],
    methods: [],
  },
  Hyperlink: {
    type: 'Hyperlink',
    label: '超链接',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Text: '打开链接', Url: 'https://www.bilibili.com', TextColor: '#1565c0', FontSize: 14 },
    fields: [
      { key: 'Text', label: '文字', kind: 'text' },
      { key: 'Url', label: '网址', kind: 'text' },
      { key: 'TextColor', label: '文字色', kind: 'color' },
      { key: 'FontSize', label: '字号', kind: 'number' },
    ],
    events: ['Click'],
    methods: [],
  },
  Divider: {
    type: 'Divider',
    label: '分割线',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Color: '#dadce0', Thickness: 1, Width: '填满父组件' },
    fields: [
      { key: 'Color', label: '颜色', kind: 'color' },
      { key: 'Thickness', label: '粗细', kind: 'number' },
    ],
    events: [],
    methods: [],
  },
  Spacer: {
    type: 'Spacer',
    label: '空白占位',
    category: 'layout',
    isVisible: true,
    isContainer: false,
    defaults: { Height: 16, Width: '填满父组件' },
    fields: [{ key: 'Height', label: '高度', kind: 'number' }],
    events: [],
    methods: [],
  },
  Badge: {
    type: 'Badge',
    label: '徽章',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Text: '新', BackgroundColor: '#e53935', TextColor: '#ffffff', FontSize: 12 },
    fields: [
      { key: 'Text', label: '文本', kind: 'text' },
      { key: 'BackgroundColor', label: '背景色', kind: 'color' },
      { key: 'TextColor', label: '文字色', kind: 'color' },
      { key: 'FontSize', label: '字号', kind: 'number' },
    ],
    events: ['Click'],
    methods: [],
  },
  Stepper: {
    type: 'Stepper',
    label: '步进器',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Value: 0, MinValue: 0, MaxValue: 99, Step: 1 },
    fields: [
      { key: 'Value', label: '当前值', kind: 'number' },
      { key: 'MinValue', label: '最小', kind: 'number' },
      { key: 'MaxValue', label: '最大', kind: 'number' },
      { key: 'Step', label: '步长', kind: 'number' },
    ],
    events: ['Changed'],
    methods: [],
  },
  RadioButton: {
    type: 'RadioButton',
    label: '单选按钮',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Text: '选项', GroupName: 'group1', Checked: false, Enabled: true },
    fields: [
      { key: 'Text', label: '文本', kind: 'text' },
      { key: 'GroupName', label: '分组名', kind: 'text' },
      { key: 'Checked', label: '选中', kind: 'boolean' },
      { key: 'Enabled', label: '启用', kind: 'boolean' },
    ],
    events: ['Changed'],
    methods: [],
  },
  SearchBar: {
    type: 'SearchBar',
    label: '搜索框',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Text: '', Hint: '搜索…', Width: '填满父组件' },
    fields: [
      { key: 'Text', label: '文本', kind: 'text' },
      { key: 'Hint', label: '提示', kind: 'text' },
    ],
    events: ['Changed', 'Submitted', 'GotFocus', 'LostFocus'],
    methods: [],
  },
  ToggleButton: {
    type: 'ToggleButton',
    label: '切换按钮',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Text: '收藏', Checked: false, BackgroundColor: '#009688', TextColor: '#ffffff' },
    fields: [
      { key: 'Text', label: '文本', kind: 'text' },
      { key: 'Checked', label: '按下态', kind: 'boolean' },
      { key: 'BackgroundColor', label: '背景色', kind: 'color' },
      { key: 'TextColor', label: '文字色', kind: 'color' },
    ],
    events: ['Changed'],
    methods: [],
  },
  Avatar: {
    type: 'Avatar',
    label: '头像',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Picture: './media/avatar.png', Size: 56, Text: '同' },
    fields: [
      { key: 'Picture', label: '图片', kind: 'asset' },
      { key: 'Size', label: '尺寸', kind: 'number' },
      { key: 'Text', label: '无图时文字', kind: 'text' },
    ],
    events: ['Click'],
    methods: [],
  },
  TabBar: {
    type: 'TabBar',
    label: '标签栏',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { ElementsFromString: '首页,发现,我的', Selection: '首页', Width: '填满父组件' },
    fields: [
      { key: 'ElementsFromString', label: '标签(逗号分隔)', kind: 'text' },
      { key: 'Selection', label: '当前选中', kind: 'text' },
    ],
    events: ['AfterSelecting'],
    methods: [],
  },
  ScrollArrangement: {
    type: 'ScrollArrangement',
    label: '滚动布局',
    category: 'layout',
    isVisible: true,
    isContainer: true,
    defaults: { Width: '填满父组件', Height: 220, BackgroundColor: 'transparent' },
    fields: [
      { key: 'Height', label: '高度', kind: 'number' },
      { key: 'BackgroundColor', label: '背景色', kind: 'color' },
    ],
    events: [],
    methods: [],
  },
  Card: {
    type: 'Card',
    label: '卡片',
    category: 'layout',
    isVisible: true,
    isContainer: true,
    defaults: { Title: '卡片标题', BackgroundColor: '#ffffff', Width: '填满父组件' },
    fields: [
      { key: 'Title', label: '标题', kind: 'text' },
      { key: 'BackgroundColor', label: '背景色', kind: 'color' },
    ],
    events: [],
    methods: [],
  },
  CoinFlip: {
    type: 'CoinFlip',
    label: '抛硬币',
    category: 'fun',
    isVisible: true,
    isContainer: false,
    defaults: { Result: '正' },
    fields: [{ key: 'Result', label: '结果', kind: 'text' }],
    events: ['Click', 'Rolled'],
    methods: ['Flip'],
  },
  TrafficLight: {
    type: 'TrafficLight',
    label: '交通灯',
    category: 'fun',
    isVisible: true,
    isContainer: false,
    defaults: { State: '红' },
    fields: [
      {
        key: 'State',
        label: '灯色',
        kind: 'select',
        options: [
          { value: '红', label: '红' },
          { value: '黄', label: '黄' },
          { value: '绿', label: '绿' },
        ],
      },
    ],
    events: ['Click', 'Changed'],
    methods: ['Next'],
  },
  LightBulb: {
    type: 'LightBulb',
    label: '灯泡',
    category: 'fun',
    isVisible: true,
    isContainer: false,
    defaults: { On: false },
    fields: [{ key: 'On', label: '点亮', kind: 'boolean' }],
    events: ['Click', 'Changed'],
    methods: [],
  },
  ScoreBoard: {
    type: 'ScoreBoard',
    label: '记分牌',
    category: 'fun',
    isVisible: true,
    isContainer: false,
    defaults: { Score: 0, Title: '得分', TextColor: '#ffffff', BackgroundColor: '#1a237e', FontSize: 32, Width: '填满父组件' },
    fields: [
      { key: 'Title', label: '标题', kind: 'text' },
      { key: 'Score', label: '分数', kind: 'number' },
      { key: 'FontSize', label: '字号', kind: 'number' },
      { key: 'TextColor', label: '文字色', kind: 'color' },
      { key: 'BackgroundColor', label: '背景色', kind: 'color' },
    ],
    events: [],
    methods: ['AddScore', 'ResetScore'],
  },
  ProgressRing: {
    type: 'ProgressRing',
    label: '环形进度',
    category: 'fun',
    isVisible: true,
    isContainer: false,
    defaults: { Percent: 35, Size: 72, Color: '#009688' },
    fields: [
      { key: 'Percent', label: '百分比', kind: 'number' },
      { key: 'Size', label: '尺寸', kind: 'number' },
      { key: 'Color', label: '颜色', kind: 'color' },
    ],
    events: [],
    methods: [],
  },
  LEDLabel: {
    type: 'LEDLabel',
    label: 'LED屏',
    category: 'fun',
    isVisible: true,
    isContainer: false,
    defaults: { Text: '88:88', TextColor: '#69f0ae', BackgroundColor: '#102027', FontSize: 28, Width: '填满父组件' },
    fields: [
      { key: 'Text', label: '文本', kind: 'text' },
      { key: 'FontSize', label: '字号', kind: 'number' },
      { key: 'TextColor', label: '文字色', kind: 'color' },
      { key: 'BackgroundColor', label: '背景色', kind: 'color' },
    ],
    events: [],
    methods: [],
  },
  FortuneBall: {
    type: 'FortuneBall',
    label: '占卜球',
    category: 'fun',
    isVisible: true,
    isContainer: false,
    defaults: { Answer: '问问我吧' },
    fields: [{ key: 'Answer', label: '回答', kind: 'text' }],
    events: ['Click', 'GotAnswer'],
    methods: ['Ask'],
  },
  LevelBar: {
    type: 'LevelBar',
    label: '血条/能量条',
    category: 'fun',
    isVisible: true,
    isContainer: false,
    defaults: { Value: 70, MaxValue: 100, Color: '#43a047', Width: '填满父组件', Height: 14 },
    fields: [
      { key: 'Value', label: '当前值', kind: 'number' },
      { key: 'MaxValue', label: '最大值', kind: 'number' },
      { key: 'Color', label: '颜色', kind: 'color' },
      { key: 'Height', label: '高度', kind: 'number' },
    ],
    events: [],
    methods: [],
  },
  BatterySensor: {
    type: 'BatterySensor',
    label: '电量传感器',
    category: 'sensors',
    isVisible: false,
    isContainer: false,
    defaults: { Enabled: true, Level: 100, Charging: false },
    fields: [{ key: 'Enabled', label: '启用', kind: 'boolean' }],
    events: ['LevelChanged'],
    methods: [],
  },
  NetworkSensor: {
    type: 'NetworkSensor',
    label: '网络传感器',
    category: 'sensors',
    isVisible: false,
    isContainer: false,
    defaults: { Enabled: true, Online: true, ConnectionType: 'unknown' },
    fields: [{ key: 'Enabled', label: '启用', kind: 'boolean' }],
    events: ['StatusChanged'],
    methods: [],
  },
  ShakeSensor: {
    type: 'ShakeSensor',
    label: '摇一摇',
    category: 'sensors',
    isVisible: false,
    isContainer: false,
    defaults: { Enabled: true, Sensitivity: 18 },
    fields: [
      { key: 'Enabled', label: '启用', kind: 'boolean' },
      { key: 'Sensitivity', label: '灵敏度', kind: 'number' },
    ],
    events: ['Shaking'],
    methods: [],
  },
  GyroscopeSensor: {
    type: 'GyroscopeSensor',
    label: '陀螺仪',
    category: 'sensors',
    isVisible: false,
    isContainer: false,
    defaults: { Enabled: true, XAngularVelocity: 0, YAngularVelocity: 0, ZAngularVelocity: 0 },
    fields: [{ key: 'Enabled', label: '启用', kind: 'boolean' }],
    events: ['GyroscopeChanged'],
    methods: [],
  },
  ProximitySensor: {
    type: 'ProximitySensor',
    label: '接近传感器',
    category: 'sensors',
    isVisible: false,
    isContainer: false,
    defaults: { Enabled: true, Distance: -1, Near: false },
    fields: [{ key: 'Enabled', label: '启用', kind: 'boolean' }],
    events: ['ProximityChanged'],
    methods: [],
  },
  Pedometer: {
    type: 'Pedometer',
    label: '计步器',
    category: 'sensors',
    isVisible: false,
    isContainer: false,
    defaults: { Enabled: true, Steps: 0, Sensitivity: 11 },
    fields: [
      { key: 'Enabled', label: '启用', kind: 'boolean' },
      { key: 'Sensitivity', label: '灵敏度', kind: 'number' },
    ],
    events: ['StepTaken'],
    methods: ['Reset'],
  },
  LightSensor: {
    type: 'LightSensor',
    label: '光线传感器',
    category: 'sensors',
    isVisible: false,
    isContainer: false,
    defaults: { Enabled: true, Illuminance: 0 },
    fields: [{ key: 'Enabled', label: '启用', kind: 'boolean' }],
    events: ['LightChanged'],
    methods: [],
  },
  MagneticFieldSensor: {
    type: 'MagneticFieldSensor',
    label: '磁场传感器',
    category: 'sensors',
    isVisible: false,
    isContainer: false,
    defaults: { Enabled: true, AbsoluteHeading: 0, MagX: 0, MagY: 0, MagZ: 0 },
    fields: [{ key: 'Enabled', label: '启用', kind: 'boolean' }],
    events: ['MagneticChanged'],
    methods: [],
  },
  Vibrator: {
    type: 'Vibrator',
    label: '震动器',
    category: 'misc',
    isVisible: false,
    isContainer: false,
    defaults: { Duration: 200 },
    fields: [{ key: 'Duration', label: '默认时长(ms)', kind: 'number' }],
    events: [],
    methods: ['Vibrate'],
  },
  Clipboard: {
    type: 'Clipboard',
    label: '剪贴板',
    category: 'misc',
    isVisible: false,
    isContainer: false,
    defaults: { Text: '' },
    fields: [],
    events: ['GotText'],
    methods: ['Copy', 'Paste'],
  },
  RandomHelper: {
    type: 'RandomHelper',
    label: '随机助手',
    category: 'misc',
    isVisible: false,
    isContainer: false,
    defaults: { LastResult: 0 },
    fields: [],
    events: ['GotResult'],
    methods: ['NextInt'],
  },
  FileSaver: {
    type: 'FileSaver',
    label: '文件保存',
    category: 'storage',
    isVisible: false,
    isContainer: false,
    defaults: { FileName: 'notes.txt' },
    fields: [{ key: 'FileName', label: '默认文件名', kind: 'text' }],
    events: [],
    methods: ['SaveFile'],
  },
  GalleryPicker: {
    type: 'GalleryPicker',
    label: '图库选择',
    category: 'media',
    isVisible: false,
    isContainer: false,
    defaults: { Selection: '' },
    fields: [],
    events: ['AfterPicking'],
    methods: ['Open'],
  },
  NotePad: {
    type: 'NotePad',
    label: '笔记库',
    category: 'storage',
    isVisible: false,
    isContainer: false,
    defaults: {
      Namespace: 'mynotes',
      Title: '',
      Content: '',
      Titles: '',
      Count: 0,
    },
    fields: [{ key: 'Namespace', label: '笔记本名称', kind: 'text' }],
    events: ['AfterSave', 'AfterLoad', 'AfterDelete', 'AfterList'],
    methods: ['SaveNote', 'LoadNote', 'DeleteNote', 'ListNotes', 'ClearAllNotes'],
  },
  FilePicker: {
    type: 'FilePicker',
    label: '文件选择',
    category: 'storage',
    isVisible: false,
    isContainer: false,
    defaults: {
      Accept: '.txt,.csv,.md,.json,text/*',
      Multiple: false,
      FileName: '',
      Content: '',
      FileNames: '',
      FileCount: 0,
      CombinedText: '',
    },
    fields: [
      { key: 'Accept', label: '文件类型(如 .txt,.csv)', kind: 'text' },
      { key: 'Multiple', label: '允许多选', kind: 'boolean' },
    ],
    events: ['AfterPicking'],
    methods: ['Open', 'OpenMultiple'],
  },
  FolderPicker: {
    type: 'FolderPicker',
    label: '文件夹选择',
    category: 'storage',
    isVisible: false,
    isContainer: false,
    defaults: {
      FolderName: '',
      FileNames: '',
      FileCount: 0,
      CombinedText: '',
      MatchLines: '',
      MatchCount: 0,
    },
    fields: [],
    events: ['AfterPicking', 'AfterSearch'],
    methods: ['OpenFolder', 'SearchInFolder'],
  },
  TextWorkshop: {
    type: 'TextWorkshop',
    label: '文本工坊',
    category: 'storage',
    isVisible: false,
    isContainer: false,
    defaults: {
      ResultText: '',
      ResultLines: '',
      ResultCount: 0,
      WordCount: 0,
      CharCount: 0,
      LineCount: 0,
    },
    fields: [],
    events: ['GotResult'],
    methods: [
      'SearchLines',
      'ReplaceAll',
      'WordStats',
      'SortLines',
      'UniqueLines',
      'ReverseLines',
      'ToUpper',
      'ToLower',
      'CsvColumn',
      'ShuffleLines',
    ],
  },
  Alarm: {
    type: 'Alarm',
    label: '闹钟',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Time: '07:00', Enabled: false, Label: '起床', Repeat: '每天', Width: '填满父组件' },
    fields: [
      { key: 'Time', label: '时间', kind: 'text' },
      { key: 'Enabled', label: '开启', kind: 'boolean' },
      { key: 'Label', label: '标签', kind: 'text' },
      { key: 'Repeat', label: '重复', kind: 'select', options: [{ value: '每天', label: '每天' }, { value: '一次', label: '一次' }] },
    ],
    events: ['AlarmFired', 'Click'],
    methods: ['Arm', 'Cancel', 'Snooze'],
  },
  CalendarView: {
    type: 'CalendarView',
    label: '日历',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: {
      Year: new Date().getFullYear(),
      Month: new Date().getMonth() + 1,
      SelectedDate: '',
      MarksFromString: '',
      Width: '填满父组件',
    },
    fields: [
      { key: 'Year', label: '年', kind: 'number' },
      { key: 'Month', label: '月', kind: 'number' },
      { key: 'SelectedDate', label: '选中日期', kind: 'text' },
      { key: 'MarksFromString', label: '标记日期(逗号)', kind: 'text' },
    ],
    events: ['AfterDateSet'],
    methods: ['GoToday', 'ShiftMonth'],
  },
  ContactList: {
    type: 'ContactList',
    label: '通讯录',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { ContactsFromString: '示例:10086', Selection: '', Width: '填满父组件', Height: 180 },
    fields: [
      { key: 'ContactsFromString', label: '联系人(姓名:电话)', kind: 'text' },
      { key: 'Height', label: '高度', kind: 'number' },
    ],
    events: ['AfterPicking'],
    methods: ['Add', 'Search'],
  },
  MapView: {
    type: 'MapView',
    label: '地图',
    category: 'media',
    isVisible: true,
    isContainer: false,
    defaults: { Latitude: 39.9, Longitude: 116.4, Zoom: 12, Width: '填满父组件', Height: 200 },
    fields: [
      { key: 'Latitude', label: '纬度', kind: 'number' },
      { key: 'Longitude', label: '经度', kind: 'number' },
      { key: 'Zoom', label: '缩放', kind: 'number' },
      { key: 'Height', label: '高度', kind: 'number' },
    ],
    events: ['Click'],
    methods: ['GoTo', 'MyLocation'],
  },
  Texting: {
    type: 'Texting',
    label: '短信',
    category: 'misc',
    isVisible: false,
    isContainer: false,
    defaults: { PhoneNumber: '', Message: '' },
    fields: [
      { key: 'PhoneNumber', label: '默认号码', kind: 'text' },
      { key: 'Message', label: '默认内容', kind: 'text' },
    ],
    events: ['MessageSent'],
    methods: ['SendMessage'],
  },
  Emailer: {
    type: 'Emailer',
    label: '邮件',
    category: 'misc',
    isVisible: false,
    isContainer: false,
    defaults: { Address: '', Subject: '' },
    fields: [
      { key: 'Address', label: '默认收件人', kind: 'text' },
      { key: 'Subject', label: '默认标题', kind: 'text' },
    ],
    events: [],
    methods: ['Send'],
  },
  Flashlight: {
    type: 'Flashlight',
    label: '手电筒',
    category: 'misc',
    isVisible: false,
    isContainer: false,
    defaults: { On: false },
    fields: [{ key: 'On', label: '打开', kind: 'boolean' }],
    events: [],
    methods: ['On', 'Off'],
  },
  SoundRecorder: {
    type: 'SoundRecorder',
    label: '录音',
    category: 'media',
    isVisible: false,
    isContainer: false,
    defaults: { Source: '' },
    fields: [],
    events: ['AfterSoundRecorded'],
    methods: ['Start', 'Stop'],
  },
  DeviceNotify: {
    type: 'DeviceNotify',
    label: '系统通知',
    category: 'misc',
    isVisible: false,
    isContainer: false,
    defaults: {},
    fields: [],
    events: ['Notified'],
    methods: ['Notify'],
  },
  BarcodeScanner: {
    type: 'BarcodeScanner',
    label: '扫码',
    category: 'media',
    isVisible: false,
    isContainer: false,
    defaults: { ScanResult: '' },
    fields: [{ key: 'ScanResult', label: '扫描结果', kind: 'text' }],
    events: ['AfterScan'],
    methods: ['Scan'],
  },
  ClockFace: {
    type: 'ClockFace',
    label: '数字时钟',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Format: 'hh:mm:ss', Style: '数字', Timezone: '本地', Text: '12:00:00', FontSize: 36, TextColor: '#69f0ae', Width: '填满父组件' },
    fields: [
      { key: 'Style', label: '样式', kind: 'select', options: [
        { value: '数字', label: '数字' },
        { value: '指针', label: '指针' },
      ] },
      { key: 'Format', label: '格式', kind: 'select', options: [
        { value: 'hh:mm:ss', label: '时:分:秒' },
        { value: 'hh:mm', label: '时:分' },
        { value: 'YYYY-MM-DD hh:mm', label: '日期时间' },
        { value: 'YYYY-MM-DD', label: '日期' },
        { value: 'W', label: '星期' },
      ] },
      { key: 'Timezone', label: '时区', kind: 'select', options: [
        { value: '本地', label: '本地' },
        { value: '8', label: '北京 UTC+8' },
        { value: '9', label: '东京 UTC+9' },
        { value: '0', label: '伦敦 UTC+0' },
        { value: '-5', label: '纽约 UTC-5' },
        { value: '10', label: '悉尼 UTC+10' },
      ] },
      { key: 'FontSize', label: '字号', kind: 'number' },
      { key: 'TextColor', label: '文字色', kind: 'color' },
    ],
    events: ['Click'],
    methods: [],
  },
  Reminder: {
    type: 'Reminder',
    label: '日程提醒',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: {
      Date: localISODate(),
      Time: '08:00',
      Enabled: false,
      Label: '提醒',
      Width: '填满父组件',
    },
    fields: [
      { key: 'Date', label: '日期', kind: 'text' },
      { key: 'Time', label: '时间', kind: 'text' },
      { key: 'Enabled', label: '开启', kind: 'boolean' },
      { key: 'Label', label: '标签', kind: 'text' },
    ],
    events: ['ReminderFired', 'Click'],
    methods: ['Arm', 'Cancel', 'Snooze'],
  },
  TodoList: {
    type: 'TodoList',
    label: '待办',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { ItemsFromString: '买菜,写作业', CheckedFromString: '', Selection: '', Width: '填满父组件', Height: 180 },
    fields: [
      { key: 'ItemsFromString', label: '事项(逗号)', kind: 'text' },
      { key: 'CheckedFromString', label: '已完成(逗号)', kind: 'text' },
      { key: 'Height', label: '高度', kind: 'number' },
    ],
    events: ['AfterChecking'],
    methods: ['Add', 'ClearDone'],
  },
  CalculatorPad: {
    type: 'CalculatorPad',
    label: '计算器',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Expression: '', Result: '0', Width: '填满父组件' },
    fields: [
      { key: 'Expression', label: '算式', kind: 'text' },
      { key: 'Result', label: '结果', kind: 'text' },
    ],
    events: ['Calculated'],
    methods: ['Press', 'Evaluate', 'Clear'],
  },
  CompassView: {
    type: 'CompassView',
    label: '指南针',
    category: 'sensors',
    isVisible: true,
    isContainer: false,
    defaults: { Heading: 0, Size: 160 },
    fields: [{ key: 'Size', label: '大小', kind: 'number' }],
    events: ['HeadingChanged', 'Click'],
    methods: [],
  },
  WeatherBox: {
    type: 'WeatherBox',
    label: '天气',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { City: '北京', Temperature: '', WeatherText: '点击获取', WindSpeed: 0, Width: '填满父组件' },
    fields: [
      { key: 'City', label: '城市', kind: 'text' },
      { key: 'Temperature', label: '气温', kind: 'text' },
      { key: 'WeatherText', label: '天气', kind: 'text' },
      { key: 'WindSpeed', label: '风速', kind: 'number' },
    ],
    events: ['AfterFetch', 'Click'],
    methods: ['Fetch'],
  },
  DialPad: {
    type: 'DialPad',
    label: '拨号盘',
    category: 'user',
    isVisible: true,
    isContainer: false,
    defaults: { Number: '', Width: '填满父组件' },
    fields: [{ key: 'Number', label: '号码', kind: 'text' }],
    events: ['NumberChanged', 'CallStarted'],
    methods: ['Press', 'Backspace', 'Call', 'Clear'],
  },
}

export const PALETTE_ORDER: ComponentType[] = [
  // 界面控件
  'Button', 'Label', 'TextBox', 'TextArea', 'NumberBox', 'PasswordTextBox', 'SearchBar',
  'CheckBox', 'RadioButton', 'Switch', 'ToggleButton', 'Slider', 'Stepper',
  'Spinner', 'TabBar', 'DatePicker', 'TimePicker', 'Alarm', 'Reminder', 'ClockFace', 'CalendarView', 'TodoList',
  'CalculatorPad', 'WeatherBox', 'ProgressBar', 'RatingBar', 'ListView',
  'ContactList', 'DialPad',
  'Hyperlink', 'Badge', 'Avatar', 'ChatBubble', 'Marquee', 'ColorPicker', 'Divider',
  // 布局
  'HorizontalArrangement', 'VerticalArrangement', 'TableArrangement', 'ScrollArrangement', 'Card', 'Spacer',
  // 媒体绘图
  'Image', 'Canvas', 'WebViewer', 'MapView', 'Player', 'VideoPlayer', 'Camera', 'GalleryPicker', 'Sound',
  'TextToSpeech', 'SpeechRecognizer', 'SoundRecorder', 'BarcodeScanner',
  // 趣味互动
  'Dice', 'CoinFlip', 'FortuneBall', 'TrafficLight', 'LightBulb',
  'Countdown', 'Stopwatch', 'ScoreBoard', 'LEDLabel', 'ProgressRing', 'LevelBar',
  'QRCode', 'Joystick', 'Ball', 'ImageSprite', 'Celebration',
  // 数据网络（笔记/文件优先）
  'NotePad', 'FilePicker', 'FolderPicker', 'TextWorkshop', 'FileSaver',
  'TinyDB', 'TinyWebDB', 'Web',
  // 传感器
  'AccelerometerSensor', 'OrientationSensor', 'CompassView', 'LocationSensor', 'GyroscopeSensor',
  'ProximitySensor', 'Pedometer', 'LightSensor', 'MagneticFieldSensor',
  'BatterySensor', 'NetworkSensor', 'ShakeSensor',
  // 工具
  'Notifier', 'Clock', 'Sharing', 'ActivityStarter', 'PhoneCall', 'Texting', 'Emailer', 'Flashlight', 'DeviceNotify', 'Vibrator', 'Clipboard', 'RandomHelper',
]

export function getMeta(type: string): ComponentMeta {
  const m = COMPONENT_REGISTRY[type]
  if (!m) throw new Error(`Unknown component: ${type}`)
  return m
}
